import './styles.css';
import './sass/sidebar.css';
import './sass/footer.css';
import './sass/header.css';
import './sass/searchForm.css';
import './sass/details.css';
import './sass/close.css';
import { mainPage } from './js/initialHomePage/initialHomePage';
import './js/libraryPage/libraryPage';
import './js/searchAndPlaginationHomePage/searchAndPlaginationHomePage';
import { initRouter } from './js/router';
mainPage();
initRouter();
